import { useState } from 'react'
import { ArrowRight, BarChart3, BatteryCharging, CarFront, Check, ChevronRight, Leaf, Menu, MessageCircle, Recycle, Sparkles, X } from 'lucide-react'
import { analyzeBusinessText } from './lib/analyzer'
import { calculateCarbonFootprint, emissionItemsFromFootprint, getRecommendations } from './lib/calculator'
import type { Analysis, EmissionItem, Source } from './types'

type View = 'home' | 'analyze' | 'result' | 'history' | 'how'
const examples = ['Hoy usamos 3 camionetas de reparto, recorrimos 250 km y consumimos 180 kWh de electricidad.', 'Este mes consumimos 3500 kWh de energía, utilizamos dos vehículos diésel y generamos 120 kg de residuos.', 'Tenemos una pequeña panadería, gastamos 800 kWh al mes y una camioneta recorre 1000 km.']
const benefits: { icon: typeof Leaf; title: string; description: string }[] = [{ icon: MessageCircle, title: 'Lenguaje cotidiano', description: 'Sin terminología ambiental complicada.' }, { icon: BarChart3, title: 'Resultado visual', description: 'Ve de inmediato qué actividad tiene más peso.' }, { icon: Leaf, title: 'Acciones útiles', description: 'Recibe ideas pequeñas, aplicables y priorizadas.' }]
const howSteps: { icon: typeof Leaf; title: string; description: string }[] = [{ icon: MessageCircle, title: '1. Interpretamos tu texto', description: 'El modo simulado identifica cantidades, unidades y actividades como electricidad, transporte y residuos.' }, { icon: BarChart3, title: '2. Aplicamos factores simples', description: 'Multiplicamos cada dato por factores de emisión centralizados y visibles, pensados para orientación educativa.' }, { icon: Leaf, title: '3. Priorizamos la acción', description: 'Mostramos qué fuente pesa más y sugerimos pasos sencillos para empezar a reducirla.' }]
const sourceIcons: Record<Source, typeof BatteryCharging> = { electricity: BatteryCharging, transport: CarFront, waste: Recycle, other: Leaf }
const sourceColor: Record<Source, string> = { electricity: '#e1aa3c', transport: '#257a5b', waste: '#78a83c', other: '#9c8f74' }
const money = new Intl.NumberFormat('es-CO', { maximumFractionDigits: 0 })

function loadHistory(): Analysis[] { try { return JSON.parse(localStorage.getItem('ecotrack-history') ?? '[]') as Analysis[] } catch { return [] } }

export default function App() {
  const [view, setView] = useState<View>('home'); const [menuOpen, setMenuOpen] = useState(false)
  const [history, setHistory] = useState<Analysis[]>(loadHistory); const [selected, setSelected] = useState<Analysis | null>(null)
  const go = (target: View) => { setView(target); setMenuOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const save = (analysis: Analysis) => { const updated = [analysis, ...history.filter(item => item.id !== analysis.id)].slice(0, 10); setHistory(updated); localStorage.setItem('ecotrack-history', JSON.stringify(updated)); setSelected(analysis); go('result') }
  return <div className="app-shell"><Header view={view} go={go} menuOpen={menuOpen} setMenuOpen={setMenuOpen} />
    <main>{view === 'home' && <Home go={go} />}{view === 'analyze' && <Analyzer onComplete={save} />}{view === 'result' && <Result analysis={selected} go={go} />}{view === 'history' && <History history={history} onOpen={item => { setSelected(item); go('result') }} go={go} />}{view === 'how' && <HowItWorks go={go} />}</main>
    <Footer go={go} /></div>
}

function Header({ view, go, menuOpen, setMenuOpen }: { view: View; go: (view: View) => void; menuOpen: boolean; setMenuOpen: (value: boolean) => void }) {
  const links: [View, string][] = [['home', 'Inicio'], ['analyze', 'Analizar mi negocio'], ['how', 'Cómo funciona'], ['history', 'Historial']]
  return <header className="site-header"><button className="brand" onClick={() => go('home')} aria-label="Ir al inicio de EcoTrack AI"><span className="brand-mark"><Leaf size={18} /></span>EcoTrack <i>AI</i></button><nav className={menuOpen ? 'nav open' : 'nav'} aria-label="Navegación principal">{links.map(([to, label]) => <button key={to} onClick={() => go(to)} className={view === to ? 'active' : ''}>{label}</button>)}</nav><button className="menu-button" aria-label="Abrir menú" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></header>
}

function Home({ go }: { go: (view: View) => void }) { return <>
  <section className="hero"><div className="hero-copy"><p className="kicker"><Sparkles size={15} /> Impacto claro para negocios reales</p><h1>Entiende la huella de carbono de tu negocio hablando con una IA.</h1><p className="lead">Describe tu día a día en tus propias palabras. EcoTrack transforma esa información en una estimación comprensible y acciones concretas.</p><div className="hero-actions"><button className="button primary" onClick={() => go('analyze')}>Analizar mi negocio <ArrowRight size={18} /></button><button className="text-button" onClick={() => go('how')}>Ver cómo funciona <ChevronRight size={17} /></button></div><p className="small-note"><Check size={15} /> Estimaciones educativas, sin registros ni tarjetas.</p></div><HeroVisual go={go} /></section>
  <section className="trust-strip"><span>Diseñada para negocios que quieren empezar</span><div><span>Pequeños comercios</span><span>Restaurantes</span><span>Servicios locales</span><span>Logística</span></div></section>
  <section className="section"><div className="section-intro"><p className="kicker">Un proceso que no pide ser experto</p><h2>De una conversación a un plan de acción.</h2></div><div className="steps">{[['01', 'Cuéntanos tu día', 'Escribe como le contarías a alguien cuánta energía, transporte o residuos utilizaste.'], ['02', 'Entiende tu impacto', 'La IA identifica los datos importantes y estima sus emisiones.'], ['03', 'Da el siguiente paso', 'Recibe recomendaciones sencillas que se ajustan a tu mayor oportunidad.']].map(([n, t, d]) => <article className="step" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="section benefits"><div className="benefit-feature"><div className="leaf-orbit"><Leaf size={34} /></div><div><p className="kicker">Hecho para el ritmo real de un negocio</p><h2>Menos formularios.<br />Más claridad.</h2><p>No necesitas conocer factores de emisión ni tener una hoja de cálculo. Solo comparte lo que ya sabes.</p><button className="text-button" onClick={() => go('analyze')}>Probar el analizador <ArrowRight size={17} /></button></div></div><div className="benefit-list">{benefits.map(({ icon: Icon, title, description }) => <article key={title}><Icon /><div><h3>{title}</h3><p>{description}</p></div></article>)}</div></section>
  <section className="final-cta"><p className="kicker">Tu primer registro toma menos de dos minutos</p><h2>Empezar es la acción más sostenible.</h2><button className="button light" onClick={() => go('analyze')}>Calcular mi huella <ArrowRight size={18} /></button></section>
</> }

function HeroVisual({ go }: { go: (view: View) => void }) { return <div className="hero-visual" aria-label="Ejemplo del resultado de un análisis"><div className="visual-glow" /><div className="chat-card"><div className="chat-title"><span className="avatar"><Leaf size={15} /></span><div><strong>EcoTrack AI</strong><small>Analizando tus actividades</small></div><span className="online" /></div><div className="user-bubble">Usamos 180 kWh y 3 camionetas recorrieron 250 km.</div><div className="ai-bubble">Ya encontré tus fuentes principales de impacto.</div></div><div className="impact-card"><span>Huella estimada este mes</span><strong>143 <small>kg CO₂e</small></strong><div className="mini-bars"><i style={{ width: '72%' }} /><i style={{ width: '39%' }} /><i style={{ width: '16%' }} /></div><button onClick={() => go('analyze')}>Ver análisis <ArrowRight size={14} /></button></div></div> }

function Analyzer({ onComplete }: { onComplete: (analysis: Analysis) => void }) { const [text, setText] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  async function submit() { if (text.trim().length < 12) { setError('Cuéntanos un poco más: incluye al menos una actividad de tu negocio.'); return }; setError(''); setLoading(true); try { const response = await analyzeBusinessText(text); const extracted = response.data; const footprint = calculateCarbonFootprint(extracted); const emissions = emissionItemsFromFootprint(footprint); if (!emissions.length) { setError('No encontramos datos medibles. Prueba incluyendo kWh, km, litros o kg de residuos.'); return }; const primary = emissions.reduce((highest, item) => item.kgCO2e > highest.kgCO2e ? item : highest); onComplete({ id: crypto.randomUUID(), createdAt: new Date().toISOString(), input: text, extracted, emissions, total: footprint.total_co2e_kg, primary, recommendations: getRecommendations(extracted, primary), notice: response.fallbackNotice }) } catch { setError('No pudimos analizar el texto. Revisa tu conexión e inténtalo de nuevo.') } finally { setLoading(false) } }
  return <section className="analyzer-page"><div className="page-heading"><p className="kicker"><MessageCircle size={15} /> Analizador inteligente</p><h1>Cuéntanos cómo funciona tu negocio.</h1><p>Escribe con naturalidad. Nosotros nos encargamos de traducir tus actividades en una estimación de impacto.</p></div><div className="analyzer-layout"><div className="prompt-panel"><div className="assistant-bar"><span className="assistant-avatar"><Sparkles size={15} /></span><div><strong>EcoTrack AI</strong><span>Listo para entender tu operación</span></div><i><b /> En línea</i></div><div className="assistant-prompt"><span>Hola, ¿qué actividades realizaron recientemente?</span><small>Incluye consumo, entregas, vehículos o residuos si los conoces.</small></div><label htmlFor="business-activity">Tu mensaje</label><textarea id="business-activity" value={text} onChange={event => setText(event.target.value)} placeholder="Hoy usamos 5 camionetas y gastamos 200 kWh de electricidad…" disabled={loading} /><div className="textarea-footer"><span>{text.length} caracteres</span><span>Enter para analizar · Shift + Enter para una línea nueva</span></div>{error && <p role="alert" className="form-error">{error}</p>}<button className="button primary analyze-button" onClick={submit} disabled={loading}>{loading ? <><span className="spinner" /> EcoTrack AI está analizando…</> : <>Analizar impacto <Sparkles size={18} /></>}</button></div><aside className="example-panel"><p>Prueba una conversación</p><h2>Elige un punto de partida</h2>{examples.map((example, i) => <button key={example} onClick={() => { setText(example); setError('') }} disabled={loading}><span>{i + 1}</span>{example}</button>)}<div className="privacy"><Check size={17} /><span>Una estimación educativa con datos que tú proporcionas.</span></div></aside></div></section> }

function Result({ analysis, go }: { analysis: Analysis | null; go: (view: View) => void }) { if (!analysis) return <Empty title="Todavía no tienes un análisis" text="Cuéntanos las actividades de tu negocio para calcular una primera estimación." action="Analizar mi negocio" go={() => go('analyze')} />; const date = new Date(analysis.createdAt).toLocaleDateString('es-CO', { day: 'numeric', month: 'long', year: 'numeric' }); return <section className="result-page"><div className="result-top"><div><button className="back" onClick={() => go('analyze')}>← Nuevo análisis</button><p className="kicker">Resultado estimado · {date}</p><h1>Tu impacto, en perspectiva.</h1></div><button className="button secondary" onClick={() => go('history')}>Ver historial</button></div><div className="result-grid"><article className="total-card"><p>Huella estimada</p><strong>{money.format(analysis.total)} <small>kg CO₂e</small></strong><span>Equivale a una estimación mensual según lo que nos contaste.</span><div className="total-card-leaf"><Leaf /></div></article><article className="primary-card"><p>Principal fuente de emisiones</p><div className="primary-source">{(() => { const Icon = sourceIcons[analysis.primary.source]; return <Icon /> })()}<div><strong>{analysis.primary.label}</strong><span>{Math.round(analysis.primary.kgCO2e / analysis.total * 100)}% de tu impacto</span></div></div><p className="plain">Priorizar esta área generará el mayor cambio.</p></article></div><p className="estimation-note">Esta estimación utiliza factores simplificados y tiene fines educativos y orientativos.</p><section className="breakdown"><div className="chart-head"><div><p className="kicker">Desglose</p><h2>¿De dónde viene tu huella?</h2></div><span>{analysis.extracted.confidence * 100}% de confianza</span></div><div className="bar-chart">{analysis.emissions.map(item => <EmissionBar item={item} total={analysis.total} key={item.source} />)}</div></section><section className="recommendations"><div><p className="kicker">Tu siguiente paso</p><h2>Acciones que podrían reducir tu impacto.</h2><p>Recomendaciones orientativas basadas en las actividades identificadas.</p></div><div className="recommendation-list">{analysis.recommendations.map((idea, index) => <article key={idea}><span>{index + 1}</span><p>{idea}</p></article>)}</div></section><div className="result-actions"><button className="button primary" onClick={() => go('analyze')}>Registrar otro mes <ArrowRight size={18} /></button></div></section> }

function EmissionBar({ item, total }: { item: EmissionItem; total: number }) { const Icon = sourceIcons[item.source]; const percent = item.kgCO2e / total * 100; return <div className="emission-row"><div className="emission-label"><span style={{ color: sourceColor[item.source] }}><Icon size={18} /></span><strong>{item.label}</strong><span>{money.format(item.kgCO2e)} kg CO₂e</span></div><div className="track"><i style={{ width: `${percent}%`, background: sourceColor[item.source] }} /></div><b>{Math.round(percent)}%</b></div> }

function History({ history, onOpen, go }: { history: Analysis[]; onOpen: (analysis: Analysis) => void; go: (view: View) => void }) { return <section className="history-page"><div className="page-heading"><p className="kicker"><BarChart3 size={15} /> Seguimiento simple</p><h1>Tu historial de impacto.</h1><p>Conservamos tus últimos análisis en este dispositivo para que puedas ver tu progreso.</p></div>{history.length === 0 ? <Empty title="Aún no hay registros" text="Tu primer análisis aparecerá aquí y podrás volver a consultarlo cuando quieras." action="Hacer mi primer análisis" go={() => go('analyze')} /> : <div className="history-list">{history.map(item => <article key={item.id}><div className="history-date"><span>{new Date(item.createdAt).toLocaleDateString('es-CO', { day: '2-digit', month: 'short' })}</span><small>{new Date(item.createdAt).getFullYear()}</small></div><div className="history-main"><strong>{money.format(item.total)} kg CO₂e</strong><span>Principal fuente: {item.primary.label}</span></div><div className="history-source"><span style={{ background: sourceColor[item.primary.source] }} />{Math.round(item.primary.kgCO2e / item.total * 100)}%</div><button onClick={() => onOpen(item)} aria-label="Ver análisis">Ver <ArrowRight size={16} /></button></article>)}</div>}</section> }

function HowItWorks({ go }: { go: (view: View) => void }) { return <section className="how-page"><div className="page-heading"><p className="kicker"><Sparkles size={15} /> Transparencia ante todo</p><h1>Cómo calcula EcoTrack AI.</h1><p>Una forma simple de convertir datos cotidianos en una señal útil para tomar mejores decisiones.</p></div><div className="how-flow">{howSteps.map(({ icon: Icon, title, description }) => <article key={title}><Icon /><h2>{title}</h2><p>{description}</p></article>)}</div><div className="disclaimer"><strong>Una estimación, no una certificación.</strong><p>Los resultados sirven para iniciar conversaciones y detectar oportunidades. Para reportes regulatorios, consulta a un especialista ambiental.</p></div><button className="button primary" onClick={() => go('analyze')}>Probar con mi negocio <ArrowRight size={18} /></button></section> }

function Empty({ title, text, action, go }: { title: string; text: string; action: string; go: () => void }) { return <div className="empty"><span><Leaf /></span><h2>{title}</h2><p>{text}</p><button className="button primary" onClick={go}>{action} <ArrowRight size={17} /></button></div> }
function Footer({ go }: { go: (view: View) => void }) { return <footer><div className="brand"><span className="brand-mark"><Leaf size={16} /></span>EcoTrack <i>AI</i></div><p>Una manera más clara de empezar a medir.</p><div><button onClick={() => go('how')}>Cómo funciona</button><button onClick={() => go('analyze')}>Analizar mi negocio</button></div></footer> }
